### ISSUE TITLE
Rewrite copy for sync button

### ISSUE THREAD

**Issue by aliya-ryan** [digidem/mapeo-desktop#117]
The text when you go to sync still isn’t very clear for a new user - would be good to have another shot at this copy.

**Comment by karissa** [comment]
Yeah, this needs to happen -- the folks at Gaia Amazonas were really confused about the interface. Also related to #139

**Comment by aliya-ryan** [comment]
So I feel like there are two quite different actions a) synchronise database (with a database someone else has sent) or b) copy database (so that someone else can sync with it or you have a backup). I wonder if having two buttons instead of one would be better. I know we've gone back and forth on this a lot with Gregor and Stephen before. But even if this isn't the perfect solution, I think it's better than the current situation.

**Comment by karissa** [comment]
Yeah, @aldopuicon also mentioned having a 'save as...' button (which is the current new, aliya's proposed 'copy')

**Comment by gmaclennan** [comment]
I think the long-form actions are:

1. Save a copy of data to synchronize with another computer
2. Synchronize with data from another computer

I think in that context "Save As..." and "Synchronize" might work. We need to avoid confusion with the "Save" action that is always present on the Mapeo main screen, which in this context means "Save my current edits to the local database".

@aldopuicon I think this is a question of design as well as wording. Do you have a copy of Mapeo? You can download a copy from https://github.com/digidem/mapeo-desktop/releases I'd be interested in your thoughts.

**Comment by aldopuicon** [comment]
Proposal for a completely different approach… After tapping "Synchronize USB", I wonder if there's a way to just display all the available databases you can synchronize to as a list, and then have an option to save as new database as the last option on that list? If there are no available databases, then the only option is to save as new database…

**Comment by gmaclennan** [comment]
@aldopuicon, I like it, but I don't think there is a way to do it. "a database to synchronize with" is a file, which can be on a USB drive or anywhere on the computer. There is not an easy way to list them. The user needs to either:

1. Use the file chooser to select an existing database to synchronize with
2. Use the file chooser to select where to save a new copy of the database

Unfortunately we are limited on that step by the operating system save / open dialogs: we have to open either the save or the open dialog and I don't think we can add buttons to them or change their behaviour. So we can control the step prior to the save or open dialog, and I think we can change the text in the title of the dialog but not sure if we can change the text on teh buttons (save / open).

**Comment by karissa** [comment]
Yeah, sounds like a cool approach. And 'save as...' could also be a `.geojson` or shapefile..

**Comment by gmaclennan** [comment]
I am still worried about the confusion of having both a "Save" and a "Save As..." button on the same screen:

![image](https://user-images.githubusercontent.com/290457/39378704-2ab0e73c-4a27-11e8-903a-363f0741ef10.png)

Both buttons do very different things. We have the save button because of iD. The actions are:

- Save: saves the current edits to the database
- Save As (as proposed): saves a copy of the entire database to a new file.

Again maybe this is a wording issue. Ideas, suggestions?

**Comment by aldopuicon** [comment]
Can we adjust the UI for the buttons that come from Mapbox? If so, it might be worth exploring what it feels like with removing the text from the button and displaying just icons. 

Also, "Save" could say "Save Edits" or "Keep Changes". Maybe "Save as…" is really "Save a copy"…? Just brainstorming. 

If the UI is not editable then maybe we do just use what we currently have and change "Synchronize USB" to "Sync Project" (maybe use the icon we are using in MM). On the next screen, it says "Sync Project to…" with options and descriptions for those options. (For example: "New Database — Use the file chooser to select where to save a new copy of the database" or "Existing Database —  Use the file chooser to select an existing database to synchronize with". Use different icons for each instead of the same folder icon (Star for "New"? Lightning Bolt for "Existing"?).

**Comment by karissa** [comment]
I like the idea of keeping "Save" or "Save Edits",  and what is currently "copy a sync file to disk" could be "Export as..."

Probably a side comment, but Gaia Amazonas folks were a bit confused about what the Save button did, wondering if there's any benefit we get from it or if its just a convention we are borrowing from iD. 

The save button currently generates a 'changeset' which is beneficial because people can add a comment about what they changed. It helps organize the history of the data. Does it make sense at all to automate creating a changeset when the person hits the 'checkmark' when generating an element, with a comment from the preset like 'generated line with [properties]'?  Are changesets cheap to generate for us on the backend ? cc @noffle

**Comment by gmaclennan** [comment]
Yes changesets are cheap to generate. This is a hangover from OSM history. In OSM you can actually open a changeset, leave it open for a few days, adding new edits to it, then close it. iD dealt with this by creating and immediately closing the changeset when you click "save". The benefit is for managing workflow: the idea is that you group edits in a changeset if they are all related to a particular task, and then write a description. It theoretically makes it easier to then review the work a user has done, but only if they actually use this functionality. OSM has active discussions around changesets sometimes, and they are rolled back as an entire changeset.

This is essentially changesets === git commits. We can just create a changeset for every edit. It just makes the history a lot noisier to review.

I'm not sure about which way to go on this though. For now, at least, I think stick to the current iD flow.

**Comment by karissa** [comment]
Yeah, I guess since we aren't reviewing the histories right now it's hard to tell if it'd be less or more noisy. It might help to see the Wao database and look at what Mapeo changesets look like in the wild, and if people are using comments that are helpful or not.

**Comment by karissa** [comment]
@aldopuicon has been working on mobile designs for sync as well as iD, which should help with this. This discussion about changesets is interesting but not necessarily related to the topic of rewriting copy for the sync button.
