### ISSUE TITLE
"Documentation Request" Creating a .mapeosettings file

### ISSUE THREAD

**Issue by LukasWillin** [digidem/mapeo-desktop#152]
Hello Digidem Devteam

This week I wanted to create my own .mapeosettings file but didnt quiet succeed. Could you provide some means of documentation on how to create one?

Because there seem to be a fiew funny characters and format rules going on.

![grafik](https://user-images.githubusercontent.com/14276298/40576406-faa9032c-60f5-11e8-83f0-e87f73a0f1e7.png)
This is from your examples file "settings-jungle-v1.0.0.mapeosettings".

I ask this because I'd like to create my own presets & settings file which I then would like to load on different installations.

Kind regards
Lukas

**Comment by noffle** [comment]
Hey Lukas. You're right: this isn't really documented. Here are some notes that might help:

- `mapeosettings` files are [tar archives](https://en.wikipedia.org/wiki/Tar_%28computing%29). It's a binary format, which is why you're seeing non-ascii characters between files (those are tar headers).
- `mapeosettings` is the byproduct of combining ID presets together in a specific way
- most of the presets we use are private, since they belong to the indigenous groups digidem works with, but there is a [public generic jungle presets repo](https://github.com/digidem/presets-jungle) that you can look at which may make the compilation process clearer

**Comment by LukasWillin** [comment]
Thank you for your response. I will have a look at it.
