### ISSUE TITLE
mapfilter doesn't like the default style.json in streets-sat-style 

### ISSUE THREAD

**Issue by karissa** [digidem/mapeo-desktop#157]
It crashes the app with a race condition. 

to reproduce, change the line in MapFilter.js:25 from 
`${osmServerHost}/styles/mapfilter-style/style.json`
 to 
`${osmServerHost}/styles/streets-sat-style/style.json`

I copied the `mapfilter-style` directly from mapfilter desktop, which seems to work for now.

**Comment by gmaclennan** [comment]
Hi @karissa I am not able to reproduce a crash here. It does fail to show the map, from what I can gather because mapeo-styles only have offline tiles in the asar for a very small area for a limited zoom range. I am not able to add any data to mapfilter to test though. Adding XML instances (from ODK) via the "+" button just seems to create a 400 error on the create observation route.
