### ISSUE TITLE
How to sync multiple databases

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#20]
I'm here in Ecuador with our partners Alianza CEIBO. We are supporting them with territory mapping of 5 indigenous nationalities, starting with the Waorani and Secoya. Each nationality will have their own database - we don't really want to mix the data right now, for legal / property right issues, and to avoid confusion. Each nationality will have their own computers, but seeing how everyone is working together in the same space here, I was thinking about the risk of syncing between two different databases.

How might we avoid this possibility? The risk is that a Secoya mapping computer syncs with a USB thumb drive, then a Waorani laptop syncs with that same USB drive, then we have a merge of both nationality's mapping data. I guess we can avoid this with training, but it would be good if in the future we can put in some kind of check to avoid someone doing this accidentally.

Once we have wireless syncing with potential auto-discovery in place the risk increases - how do with isolate databases to avoid two different databases syncing?

**Comment by substack** [comment]
Another thing to figure out is if somebody has both databases, another user should be able to selectively replicate only the parts of the database that they are interested in. Otherwise this viral replication can get out of hand. One way to implement this might be to tag documents in the db and then provide a checklist of replication tags for selective replication in the sync UI. I think that will work well for cases where there are some private pieces of data mixed in with more public data, like the position of a river. Later when syncing, perhaps the other party could also control which tags they'd like to advertise.

**Comment by mcplanner** [comment]
Sounds reasonable, as long as it doesn't make the interface too cumbersome. That would require everything have a meaningful name, and giving/selecting names would be another step in any sync.

**Comment by karissa** [comment]
@mcplanner yeah, names! closing this in favor of #75
